Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2020-11, with the labels that each got.

#17 Push image to quay.io
  Makefile
Labels: approved, size/S

#15 allow customizing configmap name
  controllers/constant/constants.go
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/M

#18 Add permission for script quay_config_docker
  common/scripts/quay_config_docker.sh
Labels: approved, size/XS

#19 Record events when create role/rolebinding Forbidden
  controllers/namespacescope_controller.go
  main.go
Labels: approved, size/S

#20 Add owner reference for the configmap
  controllers/common/util.go
  controllers/namespacescope_controller.go
Labels: approved, size/M

#22 Add finalizer
  controllers/constant/constants.go
  controllers/namespacescope_controller.go
Labels: approved, size/L

#21 update readme
  README.md
  deploy/cr.yaml
Labels: approved, lgtm, size/S

#23 fix role name in rolebinding
  OWNERS
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/XS

#24 Add bundle manifests
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator_v1_serviceaccount.yaml
  bundle/manifests/operator.ibm.com_namespacescopes.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  config/manifests/bases/ibm-namespace-scope-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
Labels: approved, size/L

#25 Add short name to crd
  bundle/manifests/ibm-namespace-scope-operator_v1_serviceaccount.yaml
  bundle/manifests/operator.ibm.com_namespacescopes.yaml
  config/crd/bases/operator.ibm.com_namespacescopes.yaml
Labels: approved, lgtm, size/XS

#27 Add authorize namespace script
  README.md
  scripts/authorize-namespace.sh
Labels: approved, size/L

#26 Use filtered cache
  controllers/constant/constants.go
  controllers/namespacescope_controller.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/M

#29 enable single namespace install mode
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-namespace-scope-operator.clusterserviceversion.yaml
Labels: approved, size/XS

#30 use ordered list for the behaviors
  README.md
Labels: approved, size/M

#31 multiple CRs managing the same configmap
  controllers/common/util.go
  controllers/constant/constants.go
  controllers/namespacescope_controller.go
  main.go
Labels: approved, lgtm, size/L

#32 Enhance generate bundle manifest
  Makefile
  PROJECT
  config/manager/manager.yaml
  config/manifests/bases/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
Labels: approved, size/L

#33 Set ibm-namespace-scope-operator sa as default
  controllers/namespacescope_controller.go
Labels: approved, size/XS

#34 don't create rbac in master namespace
  controllers/common/util.go
  controllers/namespacescope_controller.go
  main.go
Labels: approved, lgtm, size/M

#35 Remove quay push to avoid overwriting CICD push
  Makefile
Labels: approved, lgtm, size/XS

#36 Update name of role and rolebinding
  controllers/constant/constants.go
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/M

#37 Fix delete rbac issue
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/XS

#40 only copy specific role
  api/v1/namespacescope_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.ibm.com_namespacescopes.yaml
  controllers/constant/constants.go
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/L

#41 Revert "only copy specific role (#40)"
  api/v1/namespacescope_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.ibm.com_namespacescopes.yaml
  controllers/constant/constants.go
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/L

#43 bump version to 1.0.1
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#42 add ServiceAccountMembers and copy roles from service account
  api/v1/namespacescope_types.go
  api/v1/zz_generated.deepcopy.go
  config/crd/bases/operator.ibm.com_namespacescopes.yaml
  controllers/constant/constants.go
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/L

#44 update authorize script
  README.md
  scripts/authorize-namespace.sh
Labels: approved, lgtm, size/M

#45 Add service account into the name of copied role and rolebinding
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/S

#46 check if the namespace is terminating
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/XS

#47 Add validated namespace members in status
  api/v1/namespacescope_types.go
  api/v1/zz_generated.deepcopy.go
  bundle-restricted/manifests/operator.ibm.com_namespacescopes.yaml
  bundle/manifests/operator.ibm.com_namespacescopes.yaml
  config/crd/bases/operator.ibm.com_namespacescopes.yaml
  controllers/common/util.go
  controllers/namespacescope_controller.go
  scripts/authorize-namespace.sh
Labels: approved, lgtm, size/L

#48 enhance the delete logic
  controllers/namespacescope_controller.go
  scripts/authorize-namespace.sh
Labels: approved, lgtm, size/S

#49 Enhance delete rbac when comfigmap does not exist
  controllers/namespacescope_controller.go
Labels: approved, size/XS

#50 add kc link into the logs
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/XS

#51 add kc link in events
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/XS

#52 Add kc link in events
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/XS

#54 Fix create configmap
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/S
