Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2020-10, with the labels that each got.

#10 Fix code lint error
  Makefile
  OWNERS
  controllers/common/util.go
  controllers/namespacescope_controller.go
Labels: size/M

#11 restart pods after ConfigMap is updated
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/M

#12 Update makefile
  Dockerfile
  Makefile
  config/default/kustomization.yaml
  config/manager/manager.yaml
  config/rbac/cluster_role.yaml
  config/rbac/cluster_rolebinding.yaml
  config/rbac/kustomization.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/L

#13 Update role/rolebinding naming rule, add more error handling
  controllers/namespacescope_controller.go
Labels: approved, size/L

#14 Enhance update rolebinding
  Makefile
  config/manager/manager.yaml
  controllers/namespacescope_controller.go
Labels: approved, size/M
