Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2021-01, with the labels that each got.

#55 update copyright for 2021
  Makefile
  api/v1/groupversion_info.go
  api/v1/namespacescope_types.go
  api/v1/zz_generated.deepcopy.go
  common/Makefile.common.mk
  common/scripts/artifactory_config_docker.sh
  common/scripts/codecov.sh
  common/scripts/gobuild.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/multiarch_image.sh
  common/scripts/quay_config_docker.sh
  controllers/common/util.go
  controllers/constant/constants.go
  controllers/namespacescope_controller.go
  controllers/suite_test.go
  hack/boilerplate.go.txt
  main.go
  scripts/authorize-namespace.sh
  version/version.go
Labels: approved, lgtm, size/M

#56 added bitscuit to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#57 bump version to 1.1.0
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#58 updated ubi image and updated version for EUS release
  Dockerfile
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#59 update copyright for 2021 in EUS Version (#55)
  Makefile
  api/v1/groupversion_info.go
  api/v1/namespacescope_types.go
  api/v1/zz_generated.deepcopy.go
  common/Makefile.common.mk
  common/scripts/artifactory_config_docker.sh
  common/scripts/codecov.sh
  common/scripts/gobuild.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/multiarch_image.sh
  common/scripts/quay_config_docker.sh
  controllers/common/util.go
  controllers/constant/constants.go
  controllers/namespacescope_controller.go
  controllers/suite_test.go
  hack/boilerplate.go.txt
  main.go
  scripts/authorize-namespace.sh
  version/version.go
Labels: approved, lgtm, size/M

#60 switch 1.1.0 to v3 channel
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#61 updated gogo/protobuf module to v1.3.2 to fix CVE-2021-3121
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#62 Porting protof vulnerability fix to EUS
  go.mod
  go.sum
Labels: approved, lgtm, size/M

#63 fix: Fix the case, one service account has multiple roles
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/XS

#65 sync up role name
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/XS

#67 fix: checking namespace when get roles
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/XS
