Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2021-06, with the labels that each got.

#101 add Dependabot
  .github/dependabot.yml
Labels: approved, lgtm, size/XS

#103 bump operator version to 1.3.0 for release 3.9
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#104 add minKubeVersion and upgrade operator-sdk
  PROJECT
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle-restricted/manifests/operator.ibm.com_namespacescopes.yaml
  bundle-restricted/metadata/annotations.yaml
  bundle.Dockerfile
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_namespacescopes.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_namespacescopes.yaml
  config/manifests/bases/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  config/manifests/bases/ibm-namespace-scope-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#105 add minKubeVersion and upgrade operator-sdk (#104)
  PROJECT
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle-restricted/manifests/operator.ibm.com_namespacescopes.yaml
  bundle-restricted/metadata/annotations.yaml
  bundle.Dockerfile
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_namespacescopes.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_namespacescopes.yaml
  config/manifests/bases/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  config/manifests/bases/ibm-namespace-scope-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#106 update kubeVersion to 1.19.0
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  config/manifests/bases/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#108 update minkubeversion for unrestricted nss operator
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-namespace-scope-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#110 revert master branch to 3.9.0 for cd release
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#111 add deletecollection back
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/XS
