Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2021-04, with the labels that each got.

#81 updated golang to 1.15.10 and ubi8 to 8.3-291 to remediate
  Dockerfile
Labels: approved, lgtm, size/XS

#83 updated ubi8 to 8.3-298
  Dockerfile
Labels: approved, lgtm, size/XS

#84 bump namespacescope version
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#85 revert watch CR from all namespace
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  controllers/namespacescope_controller.go
  go.sum
  main.go
Labels: approved, lgtm, size/M

#86 Add @ZhuoxiLi to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#89 enhance pod refresh
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/XS

#90 add deletecollection permission
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS
