Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2021-11, with the labels that each got.

#134 bump version to 1.8.0
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#132 fix minKubeVersion
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  config/manifests/bases/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#135 go mod tidy for golang 1.17
  go.mod
Labels: size/M, approved, lgtm

#136 update golang version to 1.17.3 for EUS
  Dockerfile
  go.mod
  go.sum
Labels: size/M, approved, lgtm

#137 using specific verbs to replace wildcards
  README.md
  scripts/authorize-namespace.sh
Labels: size/M, approved, lgtm
