Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2022-01, with the labels that each got.

#144 sync up release future branch with master branch
  Dockerfile
  Makefile
  README.md
  base_images.json
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  common/scripts/codecov.sh
  common/scripts/next-csv.sh
  config/manifests/bases/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  go.mod
  scripts/authorize-namespace.sh
  version/version.go
Labels: approved, lgtm, size/L

#146 feat: Add permission filter into nss controller
  README.md
  api/v1/zz_generated.deepcopy.go
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  controllers/namespacescope_controller.go
  deploy/role.yaml
  scripts/authorize-namespace.sh
Labels: size/M, approved, lgtm

#147 update the copyrights for 2022
  Makefile
  api/v1/groupversion_info.go
  api/v1/namespacescope_types.go
  api/v1/zz_generated.deepcopy.go
  common/Makefile.common.mk
  common/scripts/artifactory_config_docker.sh
  common/scripts/gobuild.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  common/scripts/multiarch_image.sh
  common/scripts/next-csv.sh
  common/scripts/quay_config_docker.sh
  controllers/common/util.go
  controllers/constant/constants.go
  controllers/namespacescope_controller.go
  controllers/suite_test.go
  hack/boilerplate.go.txt
  main.go
  scripts/authorize-namespace.sh
  version/version.go
Labels: size/M, approved, lgtm

#149 fix vulnerability issues
  go.mod
  go.sum
Labels: approved, lgtm, size/S
