Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2022-10, with the labels that each got.

#191 update filter logic (#156)
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/XS

#192 bump version for 3.19.6
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#193 updated namespace scope version bump script
  common/scripts/next-csv.sh
Labels: size/M, approved, lgtm

#195 Revert "set value of csvInjector enable to true in nss CR (#187)"
  api/v1/namespacescope_types.go
  bundle-restricted/manifests/operator.ibm.com_namespacescopes.yaml
  bundle/manifests/operator.ibm.com_namespacescopes.yaml
  config/crd/bases/operator.ibm.com_namespacescopes.yaml
Labels: approved, lgtm, size/S

#196 Revert "[release-ltsr] set value of csvInjector enable to true in nss CR"
  api/v1/namespacescope_types.go
  bundle-restricted/manifests/operator.ibm.com_namespacescopes.yaml
  bundle/manifests/operator.ibm.com_namespacescopes.yaml
  config/crd/bases/operator.ibm.com_namespacescopes.yaml
Labels: approved, lgtm, size/S

#197 marker used to annotate presered unnknown field
  api/v1/namespacescope_types.go
  bundle-restricted/manifests/operator.ibm.com_namespacescopes.yaml
  bundle/manifests/operator.ibm.com_namespacescopes.yaml
  config/crd/bases/operator.ibm.com_namespacescopes.yaml
Labels: approved, lgtm, size/XS

#198 update protobuf to 1.3.2
  go.mod
Labels: approved, lgtm
