Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2022-07, with the labels that each got.

#169 update tool dependency for code and manifest
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle-restricted/metadata/annotations.yaml
  bundle-restricted/tests/scorecard/config.yaml
  bundle.Dockerfile
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  common/Makefile.common.mk
Labels: approved, lgtm, size/L

#170 set default value of csvinjector to true
  api/v1/namespacescope_types.go
  bundle-restricted/manifests/operator.ibm.com_namespacescopes.yaml
  bundle/manifests/operator.ibm.com_namespacescopes.yaml
  config/crd/bases/operator.ibm.com_namespacescopes.yaml
Labels: approved, lgtm, size/XS

#171 update tool dependency for code and manifest (#169)
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle-restricted/metadata/annotations.yaml
  bundle-restricted/tests/scorecard/config.yaml
  bundle.Dockerfile
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  bundle/tests/scorecard/config.yaml
  common/Makefile.common.mk
Labels: approved, lgtm, size/L

#173 compatibility clause to NSS CRDs
  bundle-restricted/manifests/operator.ibm.com_namespacescopes.yaml
  bundle/manifests/operator.ibm.com_namespacescopes.yaml
  config/crd/bases/operator.ibm.com_namespacescopes.yaml
  deploy/operator.ibm.com_namespacescopes.yaml
Labels: approved, lgtm, size/XS

#176 nss version bump to 1.13.2
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S
