Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2022-11, with the labels that each got.

#201 bump version for 3.19.7
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#202 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS

#203 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS

#204 Remove quay.io registry when building the image
  Makefile
Labels: approved, lgtm, size/XS

#205 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS
