Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2023-02, with the labels that each got.

#217 reduce permission for future NSS operator
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle-restricted/metadata/annotations.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
Labels: size/M, approved, lgtm

#218 Revert "reduce permission for future NSS operator"
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
Labels: size/M, approved, lgtm

#219 Revert "adopt multiNamespace Installation mode"
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  config/manifests/bases/ibm-namespace-scope-operator.clusterserviceversion.yaml
  controllers/common/util.go
  controllers/namespacescope_controller.go
  main.go
Labels: size/M, approved, lgtm

#221 update pkgs for twistlock
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#222 reduce NSS operator permission
  Makefile
  bundle-restricted.Dockerfile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle-restricted/manifests/operator.ibm.com_namespacescopes.yaml
  bundle-restricted/metadata/annotations.yaml
  bundle-restricted/tests/scorecard/config.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  common/scripts/next-csv.sh
  config/manifests/bases/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
Labels: approved, lgtm, size/XL

#223 bump version to 4.0.0
  Makefile
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S
