Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2023-01, with the labels that each got.

#208 bump version for 3.19.8
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#210 update go to 1.19.4
  Dockerfile
Labels: approved, lgtm, size/XS

#211 new artifactory image endpoint (namespace scope)
  Dockerfile
  Makefile
  common/scripts/artifactory_config_docker.sh
Labels: approved, lgtm, size/S

#212 [ltsr] new artifactory image endpoint (namespace scope)
  Dockerfile
  Makefile
  common/scripts/artifactory_config_docker.sh
Labels: approved, lgtm, size/S

#214 update Makefile and bundle info
  Makefile
  bundle-restricted.Dockerfile
  bundle.Dockerfile
Labels: size/M, approved, lgtm

#215 bump to v1.17.1 for v3.23.1
  Makefile
  bundle-restricted.Dockerfile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle.Dockerfile
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: size/M, approved, lgtm
