Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2023-09, with the labels that each got.

#272 update pkgs for security vulnerabilities
  go.mod
  go.sum
Labels: size/M, approved, lgtm

#268 add ephemeral-storage request to container
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, lgtm, size/XS

#273 bump version for 3.19.16
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#275 update go for twistlock
  Dockerfile
Labels: approved, lgtm, size/XS

#276 bump NSS to 4.2.1
  Makefile
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#274 Add the common label to the operand Deployment/Pod
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
Labels: lgtm, size/XS
