Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2023-04, with the labels that each got.

#230 bump NSS operator to 1.17.3 for CS 3.23.3
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#229 Ignore all ns
  common/config/.golangci.yml
  controllers/common/util.go
  controllers/namespacescope_controller.go
Labels: size/M, approved, lgtm

#233 cp3 migreate to aws
  common/Makefile.common.mk
Labels: approved, lgtm, size/XS

#234 ltsr migrate to aws
  common/Makefile.common.mk
Labels: approved, lgtm, size/XS

#235 add license accept field and idling
  api/v1/namespacescope_types.go
  api/v1/zz_generated.deepcopy.go
  bundle/manifests/operator.ibm.com_namespacescopes.yaml
  config/crd/bases/operator.ibm.com_namespacescopes.yaml
  controllers/namespacescope_controller.go
Labels: size/M, approved, lgtm
