Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2023-08, with the labels that each got.

#265 [NSS] bump version to 4.2.0
  Makefile
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#266 Bump version to 1.17.3 for 3.23.7 Fixpack
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#267 use NSS to Patch webhookconfig scope
  Makefile
  api/v1/namespacescope_types.go
  api/v1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_namespacescopes.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_namespacescopes.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  controllers/common/util.go
  controllers/constant/constants.go
  controllers/namespacescope_controller.go
  controllers/suite_test.go
  go.mod
  go.sum
Labels: approved, lgtm, size/XXL

#269 update go to 1.20.7
  Dockerfile
Labels: approved, lgtm, size/XS

#259 [LTSR] Handle NamespaceScope ENV Variable Patching issue (#258)
  controllers/common/util.go
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/L
