Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2023-10, with the labels that each got.

#279 remove namespace admin auth check
  controllers/namespacescope_controller.go
Labels: size/M, approved, lgtm

#281 bump NSS to 1.17.9 for release 2.23.9
  Makefile
  bundle-restricted/manifests/ibm-namespace-scope-operator-restricted.clusterserviceversion.yaml
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#280 Bind NSS roles' permission to the operator which contains wildcard in apiGroups or Resources
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/L

#284 update go, net pkg
  Dockerfile
  go.mod
  go.sum
Labels: size/M, approved, lgtm

#285 Keep basic permissions and remove wildcard* in NSS operator CSV
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-namespace-scope-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
Labels: approved, lgtm, size/L
