Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2024-10, with the labels that each got.

#339 Bump version to 4.2.10 for SC2 4.6.8
  Makefile
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#340 Revert "Bump golang from 1.23.0-bullseye to 1.23.1-bullseye"
  Dockerfile
Labels: size/XS

#342 Update golang to bookworm image
  Dockerfile
Labels: approved, lgtm, size/XS

#341 label length limitation
  controllers/common/util.go
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/S

#344 update RBAC with length-limited-label
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/XS

#343 Perform the RBAC propagation in parallel across namespaces
  controllers/namespacescope_controller.go
Labels: size/M, approved, lgtm

#345 Add early return in goroutine for each SA
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/XS
