Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2024-06, with the labels that each got.

#318 Security vulnerabilities LTSR June '24
  controllers/namespacescope_controller.go
  go.mod
  go.sum
Labels: approved, lgtm, size/XL

#319 Bump version to 4.2.5 for 4.6.4
  Makefile
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#320 update go restful to 3.10
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#321 removed global context from controller
  controllers/namespacescope_controller.go
Labels: approved, lgtm, size/L
