Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2025-03, with the labels that each got.

#366 updated tetheredNamespace to tetheredNamespaces
  helm/templates/02-nss-cr.yaml
  helm/values.yaml
Labels: approved, lgtm, size/XS

#367 bump nss version to 4.2.14 for cs 4.6.12
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-namespace-scope-operator.clusterserviceversion.yaml
  helm-cluster-scoped/Chart.yaml
  helm/Chart.yaml
  version/version.go
Labels: size/M, approved, lgtm

#368 updated rbac creation to create rbac in tenant namespaces
  helm/templates/00-rbac.yaml
Labels: approved, lgtm, size/S

#369 fixed helm rbac resource names
  helm/templates/00-rbac.yaml
Labels: approved, lgtm, size/XS

#371 reverted Role name to ibm-namespace-scope-operator to avoid ownership…
  helm/templates/00-rbac.yaml
Labels: approved, lgtm, size/XS

#372 update net to 0.36.0 for sc2 4.6.12
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#373 Add RELEASE_VERSION into docker build arg for RH certification
  Makefile
Labels: approved, lgtm, size/XS
