Repository IBM/ibm-namespace-scope-operator, pull requests merged in 2025-02, with the labels that each got.

#352 update image tag and chart name
  helm-cluster-scoped/Chart.yaml
  helm/templates/01-operator-deployment.yaml
  helm/values.yaml
Labels: approved, lgtm, size/XS

#355 updated chart to use globals for CPD spec
  helm-cluster-scoped/templates/01-cluster-rbac.yaml
  helm-cluster-scoped/values.yaml
  helm/templates/00-rbac.yaml
  helm/templates/01-operator-deployment.yaml
  helm/templates/02-nss-cr.yaml
  helm/values.yaml
Labels: size/M, approved, lgtm

#358 fixed incorrect tetheredNamespace reference
  helm/templates/01-operator-deployment.yaml
  helm/templates/02-nss-cr.yaml
Labels: approved, lgtm, size/XS

#357 updated chart be be installable standalone with default values
  helm/templates/02-nss-cr.yaml
  helm/values.yaml
Labels: approved, lgtm, size/S

#359 Bump version to 4.2.13 for SC2 4.6.11
  Makefile
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  version/version.go
Labels: approved, lgtm, size/S

#363 Bump NSS chart version to 4.2.13
  helm-cluster-scoped/Chart.yaml
  helm/Chart.yaml
Labels: approved, lgtm, size/XS

#364 Update NSS metadata to pass RH certification
  Dockerfile
  Makefile
  bundle.Dockerfile
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_namespacescopes.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/operator.ibm.com_namespacescopes.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/ibm-namespace-scope-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/L

#365 Update Makefile and Default Channel to v4.2
  Makefile
  api/v1/namespacescope_types.go
  api/v1/zz_generated.deepcopy.go
  bundle.Dockerfile
  bundle/manifests/ibm-namespace-scope-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_namespacescopes.yaml
  bundle/metadata/annotations.yaml
  common/Makefile.common.mk
  config/crd/bases/operator.ibm.com_namespacescopes.yaml
  config/manifests/bases/ibm-namespace-scope-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/L
